//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wares
    {
        public string GUID { get; set; }
        public string Name { get; set; }
        public string WareTypeID { get; set; }
        public float Price { get; set; }
        public float Weight { get; set; }
        public float Volume { get; set; }
        public float Piece { get; set; }
        public float TotalNum { get; set; }
        public float NumPerPiece { get; set; }
        public float TotalPrice { get; set; }
        public float OtherPrice { get; set; }
        public float ShipPrice { get; set; }
        public float SingleShipPrice { get; set; }
        public string Unit { get; set; }
        public byte[] Photo { get; set; }
        public float InsuranceRatio { get; set; }
        public string CustomerLoginID { get; set; }
        public string TruckLicense { get; set; }
        public string WareHouseID { get; set; }
        public string EmployeeID { get; set; }
        public string Statue { get; set; }
        public System.DateTime StorageTime { get; set; }
        public System.DateTime DeliverTime { get; set; }
        public System.DateTime GenerateListTime { get; set; }
        public System.DateTime PickupTime { get; set; }
        public bool TaxFree { get; set; }
        public float InsurancePrice { get; set; }
    }
}
